In [1]:
from pathlib import Path

import pandas as pd

df = pd.read_pickle('/Users/daniildegtyarev/Downloads/BTCUSDT.pkl').rename(columns={
    'time_open' : 'open_time',
    'time_close' : 'close_time'
}).drop(columns=['interval', 'symbol_id'])
INDICATORS_CONFIG_PATH = Path(
    "/Users/daniildegtyarev/Projects/roehub.com/configs/prod/indicators.yaml"
)

In [3]:
import re
import time
from pathlib import Path

import numpy as np
import pandas as pd

try:
    from trading.contexts.backtest.adapters.outbound import YamlBacktestGridDefaultsProvider
    from trading.contexts.backtest.application.services import CloseFillBacktestStagedScorerV1
    from trading.contexts.backtest.application.services.signals_from_indicators_v1 import signal_rule_spec_v1
    from trading.contexts.backtest.domain.value_objects import build_backtest_variant_key_v1
    from trading.contexts.indicators.adapters.outbound.compute_numba import NumbaIndicatorCompute
    from trading.contexts.indicators.application.dto import (
        CandleArrays,
        ComputeRequest,
        IndicatorVariantSelection,
        build_variant_key_v1,
    )
    from trading.contexts.indicators.domain.definitions import all_defs
    from trading.platform.config.indicators_compute_numba import (
        load_indicators_compute_numba_config,
    )
    from trading.shared_kernel.primitives import (
        MarketId,
        Symbol,
        Timeframe,
        TimeRange,
        UtcTimestamp,
    )
except ModuleNotFoundError as exc:
    raise RuntimeError(
        "Project dependencies are missing. Install project dependencies "
        "(for example: `uv sync`) and rerun this notebook."
    ) from exc

INDICATOR_IDS = ("ma.sma",)#, "ma.ema",)# "trend.psar", "trend.adx", "trend.linreg_slope")
ROLLUP_TIMEFRAMES = ("1h",)
MARKET_ID = 1
SYMBOL = "BTCUSDT"

BACKTEST_DIRECTION_MODE = "long-short"
BACKTEST_SIZING_MODE = "all_in"
BACKTEST_EXECUTION_PARAMS: dict[str, int | float | str | bool | None] = {}
BACKTEST_RISK_PARAMS: dict[str, int | float | str | bool | None] = {
    "sl_enabled": False,
    "sl_pct": None,
    "tp_enabled": False,
    "tp_pct": None,
}
BACKTEST_SIGNAL_PARAM_FALLBACKS: dict[str, int | float | str | bool | None] = {
    "long_delta_periods": 5,
    "short_delta_periods": 5,
    "long_threshold": 30.0,
    "short_threshold": 70.0,
    "abs_threshold": 0.1,
    "min_body_pct": 0.5,
    "min_body_atr": 0.5,
}
BACKTEST_INIT_CASH_QUOTE_DEFAULT = 10_000.0
BACKTEST_FIXED_QUOTE_DEFAULT = 100.0
BACKTEST_SAFE_PROFIT_PERCENT_DEFAULT = 30.0
BACKTEST_SLIPPAGE_PCT_DEFAULT = 0.01

required_columns = {"open_time", "close_time", "open", "high", "low", "close", "volume"}
missing_columns = sorted(required_columns.difference(df.columns))
if missing_columns:
    raise ValueError(f"`df` is missing required columns: {missing_columns}")

for col in ("open_time", "close_time"):
    series = df[col]
    if not pd.api.types.is_datetime64_any_dtype(series):
        df[col] = pd.to_datetime(series, utc=True)
    elif getattr(series.dtype, "tz", None) is None:
        df[col] = series.dt.tz_localize("UTC")

df = df.sort_values("open_time").reset_index(drop=True)

if "INDICATORS_CONFIG_PATH" not in globals():
    INDICATORS_CONFIG_PATH = Path("configs/prod/indicators.yaml")

_SUPPORTED_ENGINE_TIMEFRAMES = {"1m", "5m", "15m", "30m", "1h", "4h", "1d"}
_WARNED_ENGINE_TIMEFRAMES: set[str] = set()


def _timeframe_to_rule_and_delta(timeframe: str) -> tuple[str, pd.Timedelta]:
    value = timeframe.strip().lower()
    matched = re.fullmatch(r"(\d+)\s*([mhd])", value)
    if matched is not None:
        amount = int(matched.group(1))
        unit = matched.group(2)
        if unit == "m":
            return (f"{amount}min", pd.Timedelta(minutes=amount))
        if unit == "h":
            return (f"{amount}h", pd.Timedelta(hours=amount))
        return (f"{amount}d", pd.Timedelta(days=amount))

    delta = pd.to_timedelta(value)
    if delta <= pd.Timedelta(0):
        raise ValueError(f"Invalid timeframe: {timeframe!r}")
    return (value, delta)


def rollup_ohlcv(frame: pd.DataFrame, *, timeframe: str) -> pd.DataFrame:
    rule, delta = _timeframe_to_rule_and_delta(timeframe)
    base = frame.sort_values("open_time").reset_index(drop=True)

    rolled = (
        base.set_index("open_time")
        .resample(rule, label="left", closed="left")
        .agg(
            open=("open", "first"),
            high=("high", "max"),
            low=("low", "min"),
            close=("close", "last"),
            volume=("volume", "sum"),
        )
        .dropna(subset=["open", "high", "low", "close"])
        .reset_index()
    )

    rolled["close_time"] = rolled["open_time"] + delta - pd.Timedelta(milliseconds=1)
    return rolled[["open_time", "close_time", "open", "high", "low", "close", "volume"]]


def _engine_timeframe_code(timeframe: str) -> str:
    value = timeframe.strip().lower()
    if value in _SUPPORTED_ENGINE_TIMEFRAMES:
        return value
    if value not in _WARNED_ENGINE_TIMEFRAMES:
        print(
            f"[warn] timeframe {value!r} is not supported by Timeframe primitive; "
            "using '1m' as CandleArrays metadata for compute."
        )
        _WARNED_ENGINE_TIMEFRAMES.add(value)
    return "1m"


def dataframe_to_candles(
    frame: pd.DataFrame,
    *,
    market_id: int,
    symbol: str,
    timeframe: str,
) -> CandleArrays:
    data = frame.sort_values("open_time").reset_index(drop=True)
    ts_open = (data["open_time"].astype("int64") // 1_000_000).to_numpy(dtype=np.int64, copy=True)

    start_dt = data["open_time"].iloc[0].to_pydatetime()
    end_dt = (data["close_time"].iloc[-1] + pd.Timedelta(milliseconds=1)).to_pydatetime()

    return CandleArrays(
        market_id=MarketId(market_id),
        symbol=Symbol(symbol),
        time_range=TimeRange(start=UtcTimestamp(start_dt), end=UtcTimestamp(end_dt)),
        timeframe=Timeframe(_engine_timeframe_code(timeframe)),
        ts_open=np.ascontiguousarray(ts_open, dtype=np.int64),
        open=np.ascontiguousarray(data["open"].to_numpy(), dtype=np.float32),
        high=np.ascontiguousarray(data["high"].to_numpy(), dtype=np.float32),
        low=np.ascontiguousarray(data["low"].to_numpy(), dtype=np.float32),
        close=np.ascontiguousarray(data["close"].to_numpy(), dtype=np.float32),
        volume=np.ascontiguousarray(data["volume"].to_numpy(), dtype=np.float32),
    )


def _axis_values(axis) -> tuple[int | float | str, ...]:
    if axis.values_enum is not None:
        return tuple(axis.values_enum)
    if axis.values_int is not None:
        return tuple(int(value) for value in axis.values_int)
    if axis.values_float is not None:
        return tuple(float(value) for value in axis.values_float)
    raise ValueError(f"Axis has no values: {axis.name}")


def _decode_mixed_radix(*, flat_index: int, radices: tuple[int, ...]) -> tuple[int, ...]:
    if len(radices) == 0:
        if flat_index != 0:
            raise ValueError("flat_index must be 0 when radices are empty")
        return ()

    total = 1
    for radix in radices:
        if radix <= 0:
            raise ValueError("radices must be positive")
        total *= radix
    if flat_index < 0 or flat_index >= total:
        raise ValueError("flat_index is out of mixed-radix bounds")

    coordinates = [0] * len(radices)
    remainder = flat_index
    for position in range(len(radices) - 1, -1, -1):
        radix = radices[position]
        coordinates[position] = remainder % radix
        remainder //= radix
    return tuple(coordinates)


def _selection_from_variant_index(
    *,
    indicator_id: str,
    axes,
    variant_index: int,
) -> IndicatorVariantSelection:
    axis_values = tuple(_axis_values(axis) for axis in axes)
    radices = tuple(len(values) for values in axis_values)
    coordinates = _decode_mixed_radix(flat_index=variant_index, radices=radices)

    inputs: dict[str, int | float | str] = {}
    params: dict[str, int | float | str] = {}
    for axis, values, coordinate in zip(axes, axis_values, coordinates):
        name = axis.name.strip().lower()
        value = values[coordinate]
        if name == "source":
            inputs[name] = value
        else:
            params[name] = value

    return IndicatorVariantSelection(indicator_id=indicator_id, inputs=inputs, params=params)


def _signal_params_for_indicator(
    *,
    provider: YamlBacktestGridDefaultsProvider,
    indicator_id: str,
) -> dict[str, int | float | str | bool | None]:
    params: dict[str, int | float | str | bool | None] = {}
    defaults = provider.signal_param_defaults(indicator_id=indicator_id)
    for name in sorted(defaults.keys()):
        values = tuple(defaults[name].materialize())
        if len(values) == 0:
            raise ValueError(
                f"Signal parameter '{indicator_id}.{name}' materialized to empty values"
            )
        params[name] = values[0]

    required_params = signal_rule_spec_v1(indicator_id=indicator_id).required_signal_params
    for name in required_params:
        if name in params:
            continue
        if name not in BACKTEST_SIGNAL_PARAM_FALLBACKS:
            raise ValueError(
                f"Signal parameter '{indicator_id}.{name}' is required but has no default fallback"
            )
        params[name] = BACKTEST_SIGNAL_PARAM_FALLBACKS[name]
    return params


def run_backtest_for_selected_indicators(
    frame: pd.DataFrame,
    *,
    indicator_ids: tuple[str, ...] = INDICATOR_IDS,
    rollup_timeframes: tuple[str, ...] = ROLLUP_TIMEFRAMES,
    market_id: int = MARKET_ID,
    symbol: str = SYMBOL,
) -> pd.DataFrame:
    provider = YamlBacktestGridDefaultsProvider.from_yaml(config_path=INDICATORS_CONFIG_PATH)

    grids = {}
    for indicator_id in indicator_ids:
        grid = provider.compute_defaults(indicator_id=indicator_id)
        if grid is None:
            raise ValueError(f"No defaults grid found for {indicator_id}")
        grids[indicator_id] = grid

    signal_params_by_indicator = {
        indicator_id: _signal_params_for_indicator(
            provider=provider,
            indicator_id=indicator_id,
        )
        for indicator_id in indicator_ids
    }

    numba_cfg = load_indicators_compute_numba_config(
        environ={
            "ROEHUB_ENV": "prod",
            "ROEHUB_INDICATORS_CONFIG": str(INDICATORS_CONFIG_PATH),
        }
    )
    engine = NumbaIndicatorCompute(defs=all_defs(), config=numba_cfg)
    engine.warmup()

    instrument_id_literal = f"{market_id}:{symbol}"
    rows = []

    for timeframe in rollup_timeframes:
        rolled = rollup_ohlcv(frame, timeframe=timeframe)
        candles = dataframe_to_candles(
            rolled,
            market_id=market_id,
            symbol=symbol,
            timeframe=timeframe,
        )
        scorer = CloseFillBacktestStagedScorerV1(
            indicator_compute=engine,
            direction_mode=BACKTEST_DIRECTION_MODE,
            sizing_mode=BACKTEST_SIZING_MODE,
            execution_params=BACKTEST_EXECUTION_PARAMS,
            market_id=market_id,
            target_slice=slice(0, int(candles.ts_open.shape[0])),
            init_cash_quote_default=BACKTEST_INIT_CASH_QUOTE_DEFAULT,
            fixed_quote_default=BACKTEST_FIXED_QUOTE_DEFAULT,
            safe_profit_percent_default=BACKTEST_SAFE_PROFIT_PERCENT_DEFAULT,
            slippage_pct_default=BACKTEST_SLIPPAGE_PCT_DEFAULT,
            max_variants_guard=numba_cfg.max_variants_per_compute,
            max_compute_bytes_total=numba_cfg.max_compute_bytes_total,
        )

        for indicator_id, grid in grids.items():
            started = time.perf_counter()
            status = "ok"
            error = ""
            variants = None
            compute_elapsed_s = 0.0
            backtest_elapsed_s = 0.0
            backtest_variants_ok = 0
            backtest_variants_error = 0
            backtest_total_return_mean_pct: float | None = None
            backtest_total_return_min_pct: float | None = None
            backtest_total_return_max_pct: float | None = None

            try:
                compute_started = time.perf_counter()
                tensor = engine.compute(
                    ComputeRequest(
                        candles=candles,
                        grid=grid,
                        max_variants_guard=numba_cfg.max_variants_per_compute,
                    )
                )
                compute_elapsed_s = float(time.perf_counter() - compute_started)
                variants = int(tensor.meta.variants)

                signal_params = {indicator_id: signal_params_by_indicator[indicator_id]}
                variant_returns: list[float] = []
                first_variant_error = ""

                bt_started = time.perf_counter()
                for variant_index in range(variants):
                    try:
                        selection = _selection_from_variant_index(
                            indicator_id=indicator_id,
                            axes=tensor.axes,
                            variant_index=variant_index,
                        )
                        indicator_variant_key = build_variant_key_v1(
                            instrument_id=instrument_id_literal,
                            timeframe=timeframe,
                            indicators=(selection,),
                        )
                        variant_key = build_backtest_variant_key_v1(
                            indicator_variant_key=indicator_variant_key,
                            direction_mode=BACKTEST_DIRECTION_MODE,
                            sizing_mode=BACKTEST_SIZING_MODE,
                            signals=signal_params,
                            risk_params=BACKTEST_RISK_PARAMS,
                            execution_params=BACKTEST_EXECUTION_PARAMS,
                        )
                        metrics = scorer.score_variant_metric(
                            stage="stage_b",
                            candles=candles,
                            indicator_selections=(selection,),
                            signal_params=signal_params,
                            risk_params=BACKTEST_RISK_PARAMS,
                            indicator_variant_key=indicator_variant_key,
                            variant_key=variant_key,
                        )
                        total_return_pct = metrics.get("Total Return [%]")
                        if total_return_pct is None:
                            raise ValueError("Backtest metrics payload has no 'Total Return [%]'")
                        variant_returns.append(float(total_return_pct))
                        backtest_variants_ok += 1
                    except Exception as exc:
                        backtest_variants_error += 1
                        if not first_variant_error:
                            first_variant_error = f"{type(exc).__name__}: {exc}"
                backtest_elapsed_s = float(time.perf_counter() - bt_started)

                if variant_returns:
                    returns = np.asarray(variant_returns, dtype=np.float64)
                    backtest_total_return_mean_pct = float(np.mean(returns))
                    backtest_total_return_min_pct = float(np.min(returns))
                    backtest_total_return_max_pct = float(np.max(returns))

                if backtest_variants_error > 0:
                    status = "error"
                    error = (
                        f"Backtest failed for {backtest_variants_error}/{variants} variants; "
                        f"first error: {first_variant_error}"
                    )
            except Exception as exc:
                status = "error"
                error = f"{type(exc).__name__}: {exc}"

            elapsed_s = float(time.perf_counter() - started)
            rows.append(
                {
                    "timeframe": timeframe,
                    "bars": int(candles.ts_open.shape[0]),
                    "indicator_id": indicator_id,
                    "variants": variants,
                    "backtest_variants_ok": backtest_variants_ok,
                    "backtest_variants_error": backtest_variants_error,
                    "backtest_total_return_mean_pct": backtest_total_return_mean_pct,
                    "backtest_total_return_min_pct": backtest_total_return_min_pct,
                    "backtest_total_return_max_pct": backtest_total_return_max_pct,
                    "compute_elapsed_s": compute_elapsed_s,
                    "backtest_elapsed_s": backtest_elapsed_s,
                    "elapsed_s": elapsed_s,
                    "status": status,
                    "error": error,
                }
            )

    return pd.DataFrame(rows).sort_values(["timeframe", "indicator_id"]).reset_index(drop=True)


print(f"Rows in input df: {len(df):,}")
benchmark_df = run_backtest_for_selected_indicators(df)
benchmark_df

Rows in input df: 879,241

,timeframe,bars,indicator_id,variants,backtest_variants_ok,backtest_variants_error,backtest_total_return_mean_pct,backtest_total_return_min_pct,backtest_total_return_max_pct,compute_elapsed_s,backtest_elapsed_s,elapsed_s,status,error
0,1h,73285,ma.sma,1176,1176,0,-81.248514,-100.0,191.868514,0.948962,44.839478,45.788528,ok,

In [4]:
provider = YamlBacktestGridDefaultsProvider.from_yaml(config_path=INDICATORS_CONFIG_PATH)

grids = {}
for indicator_id in INDICATOR_IDS:
    grid = provider.compute_defaults(indicator_id=indicator_id)
    if grid is None:
        raise ValueError(f"No defaults grid found for {indicator_id}")
    grids[indicator_id] = grid

numba_cfg = load_indicators_compute_numba_config(
    environ={
        "ROEHUB_ENV": "prod",
        "ROEHUB_INDICATORS_CONFIG": str(INDICATORS_CONFIG_PATH),
    }
)

engine = NumbaIndicatorCompute(defs=all_defs(), config=numba_cfg)
engine.warmup()

grid_rows = []
for indicator_id, grid in grids.items():
    estimate = engine.estimate(
        grid=grid,
        max_variants_guard=numba_cfg.max_variants_per_compute,
    )
    grid_rows.append(
        {
            "indicator_id": indicator_id,
            "variants": int(estimate.variants),
        }
    )

pd.DataFrame(grid_rows).sort_values("indicator_id").reset_index(drop=True)

  indicator_id  variants
0       ma.sma      1176

In [4]:
if "benchmark_df" not in globals():
    benchmark_df = run_backtest_for_selected_indicators(
        df,
        indicator_ids=INDICATOR_IDS,
        rollup_timeframes=ROLLUP_TIMEFRAMES,
        market_id=MARKET_ID,
        symbol=SYMBOL,
    )
benchmark_df

[warn] timeframe '1h' is not supported by Timeframe primitive; using '1m' as CandleArrays metadata for compute.

  timeframe   bars        indicator_id  variants  elapsed_s status error
0        1h  73285              ma.ema      1176   0.694565     ok
1        1h  73285              ma.sma      1176   1.000547     ok
2        1h  73285           trend.adx      5336   4.299588     ok
3        1h  73285  trend.linreg_slope      1176   3.005527     ok
4        1h  73285          trend.psar       369   0.450810     ok

In [10]:
ok_df = benchmark_df[benchmark_df["status"] == "ok"].copy()
if ok_df.empty:
    benchmark_df
else:
    ok_df.pivot(index="timeframe", columns="indicator_id", values="elapsed_s")